[project]
name = "llm-agent-with-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.26",
    "langchain-openai>=0.3.28",
    "mcp>=1.11.0",
    "openai>=1.97.0",
]
